#!/usr/bin/env python3
"""Generate structural TBox + enum SHACL from domain.snapshot.json.

Do not hand-edit outputs — regenerate after snapshot changes.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ONTOLOGY = ROOT / ".specify" / "ontology"
SNAPSHOT = ONTOLOGY / "snapshots" / "domain.snapshot.json"
GENERATED = ONTOLOGY / "logistics_domain.generated.ttl"
ENUMS = ONTOLOGY / "logistics_domain.shacl.enums.ttl"

NS = "https://aes-lighting.internal/ns/logistics#"
GEN_IRI = "https://aes-lighting.internal/ns/logistics/generated"

CLASS_LABELS = {
    "PackingSlipCapture": "Packing Slip Capture",
    "PurchaseOrderRef": "Purchase Order Ref",
    "Project": "Project",
    "Manufacturer": "Manufacturer",
    "FileServiceUpload": "File Service Upload",
    "User": "User",
    "InventoryEntry": "Inventory Entry",
    "Delivery": "Delivery",
    "JobPmDirectory": "Job PM Directory",
    "WarehouseLocation": "Warehouse Location",
    "QrTicket": "QR Ticket",
    "DeliveryTicket": "Delivery Ticket",
}

DATA_PROPS = [
    "projectNumber",
    "poSuffix",
    "fullPO",
    "manufacturer",
    "projectName",
    "jobNumber",
    "location",
    "status",
    "role",
    "email",
    "removed",
    "removed_reason",
    "fileType",
    "extractedText",
]


def _ttl_list(values: list[str]) -> str:
    return " ".join(f'"{v}"' for v in values)


def build_generated(snap: dict) -> str:
    lines = [
        "# Logistics Domain Ontology — generated structural TBox",
        "# Regenerated by generate_ontology.py — do not hand-edit.",
        "",
        "@prefix log:  <https://aes-lighting.internal/ns/logistics#> .",
        "@prefix owl:  <http://www.w3.org/2002/07/owl#> .",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
        "@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .",
        "@prefix dct:  <http://purl.org/dc/terms/> .",
        "",
        f"<{GEN_IRI}>",
        "    a owl:Ontology ;",
        '    dct:title "logistics-express generated TBox" ;',
        f'    owl:versionInfo "{snap.get("version", "0.1.0-phase0")}" .',
        "",
        "log:LiveSurface a owl:Class ; rdfs:label \"Live Surface\" .",
        "log:DeferredDomain a owl:Class ; rdfs:label \"Deferred Domain\" .",
        "log:PublicIncomingSurface a owl:Class ; rdfs:label \"Public Incoming Surface\" .",
        "log:AuthenticatedAdminSurface a owl:Class ; rdfs:label \"Authenticated Admin Surface\" .",
        "",
        "log:UserRole a owl:Class ; rdfs:label \"User Role\" .",
        "log:InventoryStatus a owl:Class ; rdfs:label \"Inventory Status\" .",
        "log:DeliveryStatus a owl:Class ; rdfs:label \"Delivery Status\" .",
        "",
    ]

    for name in snap["entities"]["live"]:
        label = CLASS_LABELS.get(name, name)
        lines.append(
            f'log:{name} a owl:Class ; rdfs:label "{label}" ; rdfs:subClassOf log:LiveSurface .'
        )
    lines.append("")
    for name in snap["entities"]["deferred"]:
        label = CLASS_LABELS.get(name, name)
        # WarehouseLocation is both class and used for individuals — keep as DeferredDomain
        lines.append(
            f'log:{name} a owl:Class ; rdfs:label "{label}" ; rdfs:subClassOf log:DeferredDomain .'
        )
    lines.append("")

    role_map = {"driver": "RoleDriver", "pm": "RolePm", "admin": "RoleAdmin"}
    for role in snap["roles"]:
        ind = role_map[role]
        lines.append(f'log:{ind} a log:UserRole ; rdfs:label "{role}" .')
    lines.append("")

    status_map = {
        "received": "StatusReceived",
        "flagged": "StatusFlagged",
        "completed": "StatusCompleted",
        "shipped": "StatusShipped",
    }
    for st in snap["inventoryStatuses"]:
        lines.append(f'log:{status_map[st]} a log:InventoryStatus ; rdfs:label "{st}" .')
    lines.append("")

    del_map = {
        "scheduled": "DeliveryScheduled",
        "in_progress": "DeliveryInProgress",
        "completed": "DeliveryCompleted",
    }
    for st in snap["deliveryStatuses"]:
        lines.append(f'log:{del_map[st]} a log:DeliveryStatus ; rdfs:label "{st}" .')
    lines.append("")

    loc_map = {
        "Warehouse": "LocWarehouse",
        "Staging": "LocStaging",
        "Loading Bay": "LocLoadingBay",
        "Back Tent": "LocBackTent",
    }
    for loc in snap["locations"]:
        lines.append(
            f'log:{loc_map[loc]} a log:WarehouseLocation ; rdfs:label "{loc}" .'
        )
    lines.append("")

    for prop in DATA_PROPS:
        rng = "xsd:boolean" if prop == "removed" else "xsd:string"
        lines.append(f"log:{prop} a owl:DatatypeProperty ; rdfs:range {rng} .")
    lines.append("")
    return "\n".join(lines)


def build_enums(snap: dict) -> str:
    return "\n".join(
        [
            "# Logistics Domain Ontology — generated enum SHACL",
            "# Regenerated by generate_ontology.py — do not hand-edit.",
            "",
            "@prefix log:  <https://aes-lighting.internal/ns/logistics#> .",
            "@prefix sh:   <http://www.w3.org/ns/shacl#> .",
            "@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .",
            "",
            "log:UserRoleEnumShape a sh:NodeShape ;",
            "    sh:targetClass log:User ;",
            "    sh:property [",
            "        sh:path log:role ;",
            "        sh:datatype xsd:string ;",
            f"        sh:in ( {_ttl_list(snap['roles'])} ) ;",
            "    ] .",
            "",
            "log:DeliveryStatusEnumShape a sh:NodeShape ;",
            "    sh:targetClass log:Delivery ;",
            "    sh:property [",
            "        sh:path log:status ;",
            "        sh:datatype xsd:string ;",
            f"        sh:in ( {_ttl_list(snap['deliveryStatuses'])} ) ;",
            "    ] .",
            "",
            "log:InventoryStatusEnumShape a sh:NodeShape ;",
            "    sh:targetClass log:InventoryEntry ;",
            "    sh:property [",
            "        sh:path log:status ;",
            "        sh:datatype xsd:string ;",
            f"        sh:in ( {_ttl_list(snap['inventoryStatuses'])} ) ;",
            "    ] .",
            "",
            "log:WarehouseLocationEnumShape a sh:NodeShape ;",
            "    sh:targetClass log:InventoryEntry ;",
            "    sh:property [",
            "        sh:path log:location ;",
            "        sh:datatype xsd:string ;",
            f"        sh:in ( {_ttl_list(snap['locations'])} ) ;",
            "    ] .",
            "",
        ]
    )


def main() -> int:
    if not SNAPSHOT.is_file():
        print(f"error: missing {SNAPSHOT}", file=sys.stderr)
        return 1
    snap = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    GENERATED.write_text(build_generated(snap), encoding="utf-8")
    ENUMS.write_text(build_enums(snap), encoding="utf-8")
    print(f"wrote {GENERATED.relative_to(ROOT)}")
    print(f"wrote {ENUMS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
